accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("album/<int:pk>/delete/", AlbumDeleteView.as_view(), name="album_delete"),
    path("album/<int:pk>/edit/", AlbumUpdateView.as_view(), name="album_edit"),
    path("album/<int:pk>/", AlbumDetailView.as_view(), name="album_detail"),
    path("album/new/", AlbumCreateView.as_view(), name="album_new"),
    path("album", AlbumListView.as_view(), name="album"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/<int:pk>/edit/", BlogUpdateView.as_view(), name="blog_edit"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/new/", BlogCreateView.as_view(), name="blog_new"),
    path("blog", BlogListView.as_view(), name="blog"),
    path("topic", TopicListView.as_view(), name="topic"),
    path("", HomeListView.as_view(), name="home"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("blog.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Topic(models.Model):
    topic = models.CharField(max_length=200)

    def __str__(self):
        return self.topic

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE
    )
    body = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT, default=1)
    date = models.DateField(auto_now_add=True, )
    image = models.ImageField(null=True, blank=True, upload_to="blog/")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog_detail", kwargs={"pk": self.pk})

class Image(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE
    )
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT, default=1)
    date = models.DateField(auto_now_add=True, )
    image1 = models.ImageField(null=True, blank=True, upload_to="images/")
    image2 = models.ImageField(null=True, blank=True, upload_to="images/")
    image3 = models.ImageField(null=True, blank=True, upload_to="images/")
    image4 = models.ImageField(null=True, blank=True, upload_to="images/")
    image5 = models.ImageField(null=True, blank=True, upload_to="images/")
    image6 = models.ImageField(null=True, blank=True, upload_to="images/")
    image7 = models.ImageField(null=True, blank=True, upload_to="images/")
    image8 = models.ImageField(null=True, blank=True, upload_to="images/")
    image9 = models.ImageField(null=True, blank=True, upload_to="images/")


    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog_detail", kwargs={"pk": self.pk})

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post, Topic, Image

# Create your views here.
class HomeListView(ListView):
    model = Post
    template_name = "home.html"

class BlogListView(ListView):
    model = Post
    template_name = "blog.html"

class BlogDetailView(DetailView):
    model = Post
    template_name = "blog_detail.html"

class BlogCreateView(CreateView):
    model = Post
    template_name = "blog_new.html"
    fields = ["title", "topic", "body", "image",]

    def form_valid(self, form):
        form.instance.author =self.request.user
        return super().form_valid(form)

class BlogUpdateView(UpdateView):
    model = Post
    template_name = "blog_edit.html"
    fields = ["title", "topic", "body", "image",]

    def form_valid(self, form):
        form.instance.author =self.request.user
        return super().form_valid(form)

class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blog_delete.html"
    success_url = reverse_lazy("blog")

class TopicListView(ListView):
    model = Topic
    template_name = "topic.html"

class AlbumListView(ListView):
    model = Image
    template_name = "album.html"

class AlbumCreateView(CreateView):
    model = Image
    template_name = "album_new.html"
    fields = ["title", "image1", "image2", "image3", "image4", "image5", "image6", "image7", "image8", "image9"]

    def form_valid(self, form):
        form.instance.author =self.request.user
        return super().form_valid(form)

class AlbumDetailView(DetailView):
    model = Image
    template_name = "album_detail.html"

class AlbumUpdateView(UpdateView):
    model = Image
    template_name = "album_edit.html"
    fields = ["title", "image1", "image2", "image3", "image4", "image5", "image6", "image7", "image8", "image9"]

    def form_valid(self, form):
        form.instance.author =self.request.user
        return super().form_valid(form)

class AlbumDeleteView(DeleteView):
    model = Image
    template_name = "album_delete.html"
    success_url = reverse_lazy("album")

templates/album.html
{% extends "base.html" %}
{% block content %}
<h1>Albums</h1>
{% for image in image_list %}
<div class="post-entry card">
    <h2><a href = "{% url 'album_detail' image.pk %}">{{image.title}}</a></h2>
    <p>By {{image.author}}</p>
</div>
{% endfor %}
{% endblock content %}

templates/album_delete.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.id == Image.author.id %}
    <h1>Delete Album</h1>
    <form action="" method="Image">{% csrf_token %}
        <p>Are you sure you want to delete "{{ Image.title }}"?</p>
    <input type="submit" value="Confirm">
    </form >
    {% else %}
    <p>You are not authorized to delete this album!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
{% endblock content %}

templates/album_detail.html
{% extends "base.html" %}
{% block content %}
<div class="Image-entry card">
    <h2>{{ image.title }}</h2>
    <h3> By {{ image.author }}</h3>
        <p>topic: {{ image.topic }}</p>
        <p>created: {{ image.date }}</p>
        <br>
    {% if image.image1 %}
    <img src="{{image.image1.url}}" width=500>
    {% endif %}
    {% if image.image2 %}
    <img src="{{image.image2.url}}" width=500>
    {% endif %}
    {% if image.image3 %}
    <img src="{{image.image3.url}}" width=500>
    {% endif %}
    {% if image.image4 %}
    <img src="{{image.image4.url}}" width=500>
    {% endif %}
    {% if image.image5 %}
    <img src="{{image.image5.url}}" width=500>
    {% endif %}
    {% if image.image6 %}
    <img src="{{image.image6.url}}" width=500>
    {% endif %}
    {% if image.image7 %}
    <img src="{{image.image7.url}}" width=500>
    {% endif %}
    {% if image.image8 %}
    <img src="{{image.image8.url}}" width=500>
    {% endif %}
    {% if image.image9 %}
    <img src="{{image.image9.url}}" width=500>
    {% endif %}
</div>
<div class="card">
{% if user.is_authenticated %}
    {% if user.id == image.author.id %}
    <p><a href="{% url 'album_edit' image.pk %}">+ Edit Album Images</a></p>
    <p><a href="{% url 'album_delete' image.pk %}">+ Delete Album</a></p>
    {% else %}
    <p>You are not authorized to edit this album!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
</div>
{% endblock content %}

templates/album_edit.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.id == Image.author.id %}
    <h2>Edit Album</h2>
    <form action="" method="Image" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update">
    </form >
    {% else %}
    <p>You are not authorized to edit this album!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
{% endblock content %}

templates/album_new.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<h2>New Album</h2>
<form action="" method="Image" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endif %}
{% endblock content %}

templates/base.html
<html>
    {% load static %}
    <head>
        <title>My Django Blogs</title>
        <link href="{% static 'base.css' %}" rel="stylesheet" >
    </head>
    <body >
    <div >
        <header>
        <div class="header">
            <h1><a href = "{% url 'home' %}">Lee's Workshop</a></h1>
        </div>
        
        <div class="topnav">
            <a href = "{% url 'home' %}">Home</a>
            <a href = "{% url 'blog' %}">Blogs</a>
            <a href="{% url 'album' %}">Albums</a>
            <a href="{% url 'topic' %}">Topics</a>
        </div>

        <hr>
        </header>
        <div>
        <div class="column side">
            <h1>Profile</h1>
            <div class="card center left">
        {% if user.is_authenticated %}
        <img class="default-image card" src="/media/images/profile.jpg" alt="Default Profile Picture">
            <p> Welcome {{user.username}}</p>
            <div>
            <div class="button">
                <a href="{% url 'logout' %}">Log Out</a>
            </div>
        {% else %}
            <p>You are not logged in.</p>
            <div>
            <div class="button">
                <a href="{% url 'login' %}">Log In</a> 
            </div>
            <div class="button">
                <a href="{% url 'signup' %}">Sign Up</a>
            </div>
            {% endif %}
            </div>
        </div>
        </div>
        <div class="column middle excp">
        {% block content %}{% endblock content %}
        </div>
        <div class="column side">
            {% if user.is_authenticated %}
            <h1>Activities</h1>
            <div class="card center right">
            <div class="button">
                <a href="{% url 'blog_new' %}">+ New Blog Post</a>
            </div>
            <div class="button">
                <a href="{% url 'album_new' %}">+ New Album Images</a>
            </div>
        {% else %}
            <a>  </a>
        {% endif %}
        </div>
        </div>
        </div>
        <div class="footer">
            <p> Copyright <span>&copy;</span> 2024, Stanlie Joannis</p>
        </div>
    </body>
</html>

templates/blog.html
{% extends "base.html" %}
{% block content %}
<h1>Blogs</h1>
{% for post in post_list %}
<div class="post-entry card">
    <h2><a href = "{% url 'blog_detail' post.pk %}">{{post.title}}</a></h2>
    <p>{{post.body|truncatechars:30}}</p>
</div>
{% endfor %}
{% endblock content %}

templates/blog_delete.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm">
    </form >
    {% else %}
    <p>You are not authorized to delete this blog!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
{% endblock content %}

templates/blog_detail.html
{% extends "base.html" %}
{% block content %}
<div class="post-entry card">
    <h2>{{ post.title }}</h2>
    <h3> by {{ post.author }}</h3>
        <p>topic: {{ post.topic }}</p>
        <p>created: {{ post.date }}</p>
        <br>
    <p>{{ post.body }}</p>
    {% if post.image %}
    <img src="{{post.image.url}}" width=500>
    {% endif %}
</div>
<div class="card">
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <p><a href="{% url 'blog_edit' post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url 'blog_delete' post.pk %}">+ Delete Blog Post</a></p>
    {% else %}
    <p>You are not authorized to edit this blog!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
</div>
{% endblock content %}

templates/blog_edit.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
    <h2>Edit post</h2>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Update">
    </form >
    {% else %}
    <p>You are not authorized to edit this blog!</p>
    {% endif %}
{% else %}
<p>Please Log In</p>
{% endif %}
{% endblock content %}

templates/blog_new.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<h2>New post</h2>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endif %}
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block content %}
<h1>Home</h1>
<div class="card">
    <div class="button">
        <a href = "{% url 'blog' %}">Blogs</a>
    </div>
    <div class="button">
        <a href="{% url 'album' %}">Albums</a>
    </div>
    <div class="button">
        <a href="{% url 'topic' %}">Topics</a>
    </div>
</div>
{% endblock content %}

templates/topic.html
{% extends "base.html" %}
{% block content %}
<h1>Blog Topic</h1>
<ul class="no-bullets">
    {% for topic in topic_list %}
    <div class="card">
    <li>Topic: {{ topic }} </li>
    <ol>
        {% for post in topic.post_set.all %}
        <a href = "{% url 'blog_detail' post.pk %}">
        <li>{{post.title}}</li></a>
        {% endfor %}
    </ol>
    </div>
    {% endfor %}
</ul>
{% endblock content %}